"""First Database

Revision ID: 652fb5bd1179
Revises: 
Create Date: 2021-04-29 11:35:15.765299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652fb5bd1179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Building_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(length=64), nullable=True),
    sa.Column('adress', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('zip', sa.String(length=64), nullable=True),
    sa.Column('bldg_class', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('available_area', sa.Integer(), nullable=True),
    sa.Column('vacancy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adress'),
    sa.UniqueConstraint('building_name')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('testing_field', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vacant_suite_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_number', sa.String(length=64), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['Building_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacant_suite_table')
    op.drop_table('user_table')
    op.drop_table('Building_table')
    # ### end Alembic commands ###
